// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ZgjedhjetApi.Data;

#nullable disable

namespace ZgjedhjetApi.Migrations
{
    [DbContext(typeof(LifeDbContext))]
    [Migration("20260124223659_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ZgjedhjetApi.Models.Entities.Zgjedhjet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Kategoria")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Kategoria");

                    b.Property<string>("Komuna")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Komuna");

                    b.Property<string>("Qendra_e_votimit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Qendra_e_votimit");

                    b.Property<string>("Vendvotimi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Vendvotimi");

                    b.HasKey("Id");

                    b.ToTable("Zgjedhjet", (string)null);
                });

            modelBuilder.Entity("ZgjedhjetApi.Models.Entities.Zgjedhjet", b =>
                {
                    b.OwnsOne("ZgjedhjetApi.Models.Entities.PartiaVotes", "Partia", b1 =>
                        {
                            b1.Property<int>("ZgjedhjetId")
                                .HasColumnType("int");

                            b1.Property<int>("Partia111")
                                .HasColumnType("int");

                            b1.Property<int>("Partia112")
                                .HasColumnType("int");

                            b1.Property<int>("Partia113")
                                .HasColumnType("int");

                            b1.Property<int>("Partia114")
                                .HasColumnType("int");

                            b1.Property<int>("Partia115")
                                .HasColumnType("int");

                            b1.Property<int>("Partia116")
                                .HasColumnType("int");

                            b1.Property<int>("Partia117")
                                .HasColumnType("int");

                            b1.Property<int>("Partia118")
                                .HasColumnType("int");

                            b1.Property<int>("Partia119")
                                .HasColumnType("int");

                            b1.Property<int>("Partia120")
                                .HasColumnType("int");

                            b1.Property<int>("Partia121")
                                .HasColumnType("int");

                            b1.Property<int>("Partia122")
                                .HasColumnType("int");

                            b1.Property<int>("Partia123")
                                .HasColumnType("int");

                            b1.Property<int>("Partia124")
                                .HasColumnType("int");

                            b1.Property<int>("Partia125")
                                .HasColumnType("int");

                            b1.Property<int>("Partia126")
                                .HasColumnType("int");

                            b1.Property<int>("Partia127")
                                .HasColumnType("int");

                            b1.Property<int>("Partia128")
                                .HasColumnType("int");

                            b1.Property<int>("Partia129")
                                .HasColumnType("int");

                            b1.Property<int>("Partia130")
                                .HasColumnType("int");

                            b1.Property<int>("Partia131")
                                .HasColumnType("int");

                            b1.Property<int>("Partia132")
                                .HasColumnType("int");

                            b1.Property<int>("Partia133")
                                .HasColumnType("int");

                            b1.Property<int>("Partia134")
                                .HasColumnType("int");

                            b1.Property<int>("Partia135")
                                .HasColumnType("int");

                            b1.Property<int>("Partia136")
                                .HasColumnType("int");

                            b1.Property<int>("Partia137")
                                .HasColumnType("int");

                            b1.Property<int>("Partia138")
                                .HasColumnType("int");

                            b1.HasKey("ZgjedhjetId");

                            b1.ToTable("Zgjedhjet");

                            b1.WithOwner()
                                .HasForeignKey("ZgjedhjetId");
                        });

                    b.Navigation("Partia")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
